// The dashboard snapshot — the ONLY data that leaves your machine.
// Regenerated by /sync from journal/; secret-free by contract (nothing from
// journal/health.md, no keys, no raw entries). The template ships with a
// FICTIONAL example person so the dashboard renders out of the box.

export type TrendPoint = { date: string; value: number }; // real dated readings only

export type Metric = {
  key: string;
  label: string;
  unit: string;
  decimals?: number;
  current: number;
  weeklyAverage?: number;
  higherIsBetter: boolean;
  trend: TrendPoint[];
};

export type Tier = "under" | "target" | "over";

export type RunSegment = { label: string; intensity: "easy" | "mod" | "hard"; widthPct: number };
export type StrengthSet = { exercise: string; sets: number; reps: string; rpe?: number; weight?: string };

export type SessionTier = {
  title: string;
  meta: string;
  why: string;
  segments?: RunSegment[]; // run-style sessions
  strength?: StrengthSet[]; // prescribed strength (only if opted in via journal/training.md)
};

export type Session = {
  day: string; // "Mon"
  date: string; // YYYY-MM-DD
  label: string;
  kind: "run" | "strength" | "other" | "rest";
  status: "done" | "today" | "upcoming" | "rest";
  note?: string; // self-reported context — the sync preserves these
  tiers?: Partial<Record<Tier, SessionTier>>; // day-of only by default
};

export type PersonData = {
  headline: { label: string; value: string; detail: string };
  metrics: Metric[]; // readiness + hrv (if present) drive the suggested tier
  week: Session[];
  coachNote: string;
};

export type Person = { id: string; name: string; data: PersonData };

export type GateConfig = {
  username: string;
  saltHex: string;
  iterations: number;
  hashHex: string; // PBKDF2-SHA-256(password, salt, iterations) — plaintext is never stored
};

export type Snapshot = {
  updatedAt: string;
  gate: GateConfig | null;
  supabase: { url: string; anonKey: string } | null; // insert-only inbox (docs/supabase.md)
  people: Person[];
};

// ---------------------------------------------------------------------------
// FICTIONAL example data ("Alex Example") — replace via /initiate and /sync.
// Sparse trend points are deliberate: real data is sparse; never interpolate.
// ---------------------------------------------------------------------------

export const snapshot: Snapshot = {
  updatedAt: "2026-07-10",
  gate: null, // /initiate fills this via `npm run gate-hash` if a gate is wanted
  supabase: null, // fill { url, anonKey } after docs/supabase.md setup
  people: [
    {
      id: "alex",
      name: "Alex Example",
      data: {
        headline: {
          label: "Predicted 10K",
          value: "52:30",
          detail: "goal: sub-50 by November — plan assumes HRV avg 52 and 3 run days/week",
        },
        metrics: [
          {
            key: "readiness", label: "Readiness", unit: "/ 100", current: 74, weeklyAverage: 66, higherIsBetter: true,
            trend: [
              { date: "2026-06-12", value: 58 }, { date: "2026-06-19", value: 61 }, { date: "2026-06-26", value: 55 },
              { date: "2026-07-01", value: 63 }, { date: "2026-07-04", value: 70 }, { date: "2026-07-07", value: 66 },
              { date: "2026-07-09", value: 71 }, { date: "2026-07-10", value: 74 },
            ],
          },
          {
            key: "hrv", label: "HRV", unit: "ms", current: 55, weeklyAverage: 52, higherIsBetter: true,
            trend: [
              { date: "2026-06-12", value: 49 }, { date: "2026-06-20", value: 51 }, { date: "2026-06-27", value: 50 },
              { date: "2026-07-02", value: 52 }, { date: "2026-07-05", value: 53 }, { date: "2026-07-08", value: 51 },
              { date: "2026-07-10", value: 55 },
            ],
          },
          {
            key: "rhr", label: "Resting HR", unit: "bpm", current: 57, weeklyAverage: 58, higherIsBetter: false,
            trend: [
              { date: "2026-06-15", value: 60 }, { date: "2026-06-25", value: 59 }, { date: "2026-07-03", value: 58 },
              { date: "2026-07-07", value: 58 }, { date: "2026-07-10", value: 57 },
            ],
          },
          {
            key: "calin", label: "Calories in", unit: "kcal", current: 2650, weeklyAverage: 2280, higherIsBetter: true,
            trend: [
              { date: "2026-07-04", value: 2200 }, { date: "2026-07-05", value: 2150 }, { date: "2026-07-06", value: 2300 },
              { date: "2026-07-07", value: 2100 }, { date: "2026-07-08", value: 2250 }, { date: "2026-07-09", value: 2650 },
            ],
          },
          {
            key: "balance", label: "Energy balance", unit: "kcal", current: 320, weeklyAverage: -120, higherIsBetter: true,
            trend: [
              { date: "2026-07-04", value: -180 }, { date: "2026-07-05", value: -250 }, { date: "2026-07-06", value: -90 },
              { date: "2026-07-07", value: -310 }, { date: "2026-07-08", value: -150 }, { date: "2026-07-09", value: 320 },
            ],
          },
        ],
        week: [
          { day: "Sun", date: "2026-07-05", label: "Easy 5K", kind: "run", status: "done" },
          { day: "Mon", date: "2026-07-06", label: "Upper body", kind: "strength", status: "done" },
          {
            day: "Tue", date: "2026-07-07", label: "Easy 4K", kind: "run", status: "done",
            note: "Self-reported: legs heavy, kept it to 3K — readiness said 66 but it felt like less.",
          },
          { day: "Wed", date: "2026-07-08", label: "Rest", kind: "rest", status: "rest" },
          { day: "Thu", date: "2026-07-09", label: "Lower body", kind: "strength", status: "done" },
          {
            day: "Fri", date: "2026-07-10", label: "Intervals 6x400", kind: "run", status: "today",
            tiers: {
              under: {
                title: "Easy Run · 4K", meta: "intervals dropped — all conversational",
                why: "Not feeling 100: convert the quality day to easy volume, keep the habit.",
                segments: [{ label: "4K conversational", intensity: "easy", widthPct: 100 }],
              },
              target: {
                title: "Intervals · 6x400m", meta: "warm up → 6x400 @ 5K effort, 90s jog → cool down",
                why: "The baseline session — hold even splits, finish knowing you had one more rep.",
                segments: [
                  { label: "1.5K warm up", intensity: "easy", widthPct: 30 },
                  { label: "6x400m @ 5K effort", intensity: "hard", widthPct: 45 },
                  { label: "1.2K cool down", intensity: "easy", widthPct: 25 },
                ],
              },
              over: {
                title: "Intervals · 8x400m", meta: "two extra reps, same effort ceiling",
                why: "Feeling 200 — ONLY if readiness and HRV are both above baseline today (they are: 74 vs 66, 55 vs 52). Last night's +320 kcal is glycogen in the bank — the cheat meal bought these two reps. Extra reps, not faster reps.",
                segments: [
                  { label: "1.5K warm up", intensity: "easy", widthPct: 26 },
                  { label: "8x400m @ 5K effort", intensity: "hard", widthPct: 52 },
                  { label: "1.2K cool down", intensity: "easy", widthPct: 22 },
                ],
              },
            },
          },
          {
            day: "Sat", date: "2026-07-11", label: "Full body", kind: "strength", status: "upcoming",
            tiers: {
              target: {
                title: "Full body · prescribed", meta: "example of opted-in set/rep/RPE prescription",
                why: "Loads calibrated to journal/training.md working weights; RPE caps the day.",
                strength: [
                  { exercise: "Squat", sets: 3, reps: "5", rpe: 7, weight: "80 kg" },
                  { exercise: "Bench Press", sets: 3, reps: "6-8", rpe: 8, weight: "60 kg" },
                  { exercise: "Row", sets: 3, reps: "8-10", rpe: 8 },
                ],
              },
            },
          },
        ],
        coachNote:
          "Readiness 74 against a 66 average, HRV 55 over its 52 baseline, and yesterday's surplus in the tank — today is the day the overreach tier exists for. Worth watching: the last two below-baseline sessions both came two days after 300+ kcal deficit days (2 instances — a hypothesis, not a law yet). This is fictional example data — run /initiate to make it yours.",
      },
    },
  ],
};
